name:                honeycomb
version:             0.1.0.1
github:              "iand675/hs-honeycomb"
license:             BSD3
author:              "Ian Duncan, Jade Lovelace"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan, 2022 Mercury Technologies, Inc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/honeycomb#readme>

default-extensions:
- GADTs
- GeneralizedNewtypeDeriving
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- async
- unliftio
- monad-control
- chronos
- aeson >= 2.0
- mtl
- text
- vector
- uuid
- mwc-random
- random >= 1.2
- unordered-containers
- http-conduit
- http-client
- http-client-tls
- http-types
- zlib
- bytestring
- stm
- uuid
- auto-update
- microlens
- mmorph
- resource-pool
- profunctors

library:
  source-dirs: src
  exposed-modules:
    - Honeycomb
    - Honeycomb.API.Events
    - Honeycomb.API.Markers
    - Honeycomb.API.Types
    - Honeycomb.API.Auth
    - Honeycomb.Config
    - Honeycomb.Types

tests:
  honeycomb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honeycomb
